# Social Media Addiction Analysis

In [1]:
pip install numpy

Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_excel("Uncleaned_social_media_dataset_with_userid.xlsx")

In [4]:
df.head()

,User_ID,Date,App_Name,Usage_Hours,Sleep_Hours,Productivity_Score,Mood,Study_Hours,Notification_Count,Screen_Unlocks,Weekend_Usage
0,USER_0001,2026-03-23,YouTube,0.7,5,94,Tired,5.5,67,65.0,No
1,USER_0002,2026-04-05,YouTube,6.6,8.4,53,Focused,1.2,141,87.0,No
2,USER_0003,2026-02-24,Instagram,0.8,4.7,91,Focused,2.9,105,75.0,Yes
3,USER_0004,2026-01-04,Facebook,6.9,7.4,31,Tired,2.6,228,24.0,No
4,USER_0005,2026-02-27,Snapchat,7.8,3.5,37,Neutral,6.2,268,59.0,No
5,USER_0006,2026-02-24,Telegram,3.0,4.7,73,Happy,5.7,266,83.0,Yes
6,USER_0007,2026-01-12,Twitter,1.4,8.2,84,Lazy,7.2,129,34.0,No
7,USER_0008,2026-04-14,Instagram,7.1,6.4,29,Happy,1.6,225,42.0,No
8,USER_0009,2026-03-12,Snapchat,8.0,6.9,NaN,Focused,4.0,50,15.0,No
9,USER_0010,2026-01-25,YouTube,0.9,4.8,91,Happy,1.2,104,100.0,No
10,USER_0011,2026-04-20,Facebook,8.3,5.6,17,Neutral,2.5,214,65.0,Yes
11,USER_0012,2026-04-17,Telegram,2.0,5.5,76,Lazy,4.5,21,10.0,No
12,USER_0013,2026-03-31,YouTube,6.0,4.4,28,Tired,1.2,219,76.0,Yes
13,USER_0014,2026-01-21,LinkedIn,3.9,NaN,53,Neutral,2.4,155,113.0,NaN
14,USER_0015,2026-03-13,Facebook,6.7,8.1,53,Tired,5.5,252,78.0,No
15,USER_0016,2026-04-16,Instagram,7.7,5.7,46,Tired,4.8,166,97.0,No
16,USER_0017,2026-04-27,Telegram,2.4,6.2,71,Stressed,2.5,236,102.0,Yes
17,USER_0018,2026-01-19,Snapchat,1.8,7.6,80,Lazy,5.1,304,104.0,No
18,USER_0019,NaN,Twitter,8.6,5.7,31,Tired,6.7,269,104.0,No
19,USER_0020,2026-03-07,LinkedIn,1.3,3.8,90,Tired,1.0,99,95.0,No
20,USER_0021,2026-03-22,WhatsApp,7.6,5.8,46,Stressed,6.6,117,35.0,Yes
21,USER_0022,2026-02-18,LinkedIn,5.3,8.8,62,Neutral,5.9,171,56.0,No
22,USER_0023,2026-04-03,YouTube,6.6,6.5,40,Neutral,3.4,131,65.0,Yes
23,USER_0024,2026-02-13,YouTube,3.1,4.4,78,Neutral,2.1,49,18.0,Yes
24,USER_0025,2026-04-23,Snapchat,9.2,7.7,10,Happy,7.7,316,95.0,No
25,USER_0026,2026-04-22,Snapchat,8.1,6.3,35,Tired,3.4,297,52.0,Yes
26,USER_0027,2026-02-17,WhatsApp,5.4,7.8,40,Happy,1.6,51,89.0,Yes
27,USER_0028,2026-03-18,Telegram,4.9,4.1,55,Lazy,1.7,180,50.0,No
28,USER_0029,2026-01-31,Instagram,2.7,6.6,81,Happy,6.9,49,94.0,Yes
29,USER_0030,2026-04-04,LinkedIn,7.8,8.9,14,Tired,5.2,45,118.0,No
30,USER_0031,2026-01-17,LinkedIn,9.0,4.4,10,Focused,6.6,319,25.0,Yes
31,USER_0032,2026-02-24,Facebook,8.9,7.7,10,Tired,6.1,264,102.0,Yes
32,USER_0033,2026-04-02,Snapchat,4.1,7.2,63,Stressed,4.8,277,48.0,No
33,USER_0034,2026-04-26,LinkedIn,1.6,NaN,85,Happy,7.8,291,74.0,No
34,USER_0035,2026-03-17,Facebook,5.8,3.5,30,Neutral,3.6,100,49.0,No
35,USER_0036,2026-01-08,Facebook,1.1,3.7,90,Happy,4.9,49,95.0,NaN
36,USER_0037,2026-03-07,Facebook,3.0,6.2,67,Tired,6.8,280,62.0,No
37,USER_0038,2026-04-03,LinkedIn,2.7,6.1,73,Tired,5.3,61,51.0,No
38,USER_0039,2026-01-13,YouTube,6.4,5.4,36,Stressed,7.0,115,61.0,No
39,USER_0040,2026-04-21,Instagram,6.6,ERROR_VALUE,53,Happy,5.0,55,99.0,No
40,USER_0041,2026-02-21,Telegram,7.7,4.1,38,Tired,5.9,324,47.0,No
41,USER_0042,2026-03-10,LinkedIn,1.8,4.5,82,Tired,1.3,54,80.0,No
42,USER_0043,2026-04-22,YouTube,4.5,8.2,50,NaN,2.6,140,26.0,No
43,USER_0044,2026-01-07,Instagram,9.2,8.6,26,Tired,3.0,226,34.0,Yes
44,USER_0045,2026-02-22,LinkedIn,NaN,8.3,66,Tired,1.6,81,63.0,No
45,USER_0046,2026-02-18,Instagram,9.4,5,10,Lazy,2.6,311,95.0,Yes
46,USER_0047,2026-02-24,LinkedIn,1.9,5.1,86,Focused,1.7,146,58.0,Yes
47,USER_0048,2026-04-05,Instagram,7.2,3.8,20,Stressed,2.9,316,96.0,No
48,USER_0049,NaN,WhatsApp,1.0,6.3,92,Happy,5.4,324,105.0,Yes
49,USER_0050,2026-03-18,YouTube,6.6,4.8,53,Focused,3.6,40,32.0,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_ID             202 non-null    object
 1   Date                200 non-null    object
 2   App_Name            201 non-null    object
 3   Usage_Hours         197 non-null    float64
 4   Sleep_Hours         195 non-null    object
 5   Productivity_Score  201 non-null    object
 6   Mood                195 non-null    object
 7   Study_Hours         198 non-null    float64
 8   Notification_Count  202 non-null    int64
 9   Screen_Unlocks      200 non-null    float64
 10  Weekend_Usage       200 non-null    object
dtypes: float64(3), int64(1), object(7)
memory usage: 17.5+ KB

In [7]:
df.isnull().sum()

User_ID               0
Date                  2
App_Name              1
Usage_Hours           5
Sleep_Hours           7
Productivity_Score    1
Mood                  7
Study_Hours           4
Notification_Count    0
Screen_Unlocks        2
Weekend_Usage         2
dtype: int64

In [8]:

df['Sleep_Hours'] = pd.to_numeric(df['Sleep_Hours'], errors='coerce')
df['Productivity_Score'] = pd.to_numeric(df['Productivity_Score'], errors='coerce')


numeric_cols = df.select_dtypes(include=['int64','float64']).columns

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

print(df.head(50))
#print(df[numeric_cols])

      User_ID        Date   App_Name  Usage_Hours  Sleep_Hours  \
0   USER_0001  2026-03-23    YouTube     0.700000     5.000000
1   USER_0002  2026-04-05    YouTube     6.600000     8.400000
2   USER_0003  2026-02-24  Instagram     0.800000     4.700000
3   USER_0004  2026-01-04   Facebook     6.900000     7.400000
4   USER_0005  2026-02-27   Snapchat     7.800000     3.500000
5   USER_0006  2026-02-24   Telegram     3.000000     4.700000
6   USER_0007  2026-01-12    Twitter     1.400000     8.200000
7   USER_0008  2026-04-14  Instagram     7.100000     6.400000
8   USER_0009  2026-03-12   Snapchat     8.000000     6.900000
9   USER_0010  2026-01-25    YouTube     0.900000     4.800000
10  USER_0011  2026-04-20   Facebook     8.300000     5.600000
11  USER_0012  2026-04-17   Telegram     2.000000     5.500000
12  USER_0013  2026-03-31    YouTube     6.000000     4.400000
13  USER_0014  2026-01-21   LinkedIn     3.900000     6.258639
14  USER_0015  2026-03-13   Facebook     6.700000     8.100000
15  USER_0016  2026-04-16  Instagram     7.700000     5.700000
16  USER_0017  2026-04-27   Telegram     2.400000     6.200000
17  USER_0018  2026-01-19   Snapchat     1.800000     7.600000
18  USER_0019         NaN    Twitter     8.600000     5.700000
19  USER_0020  2026-03-07   LinkedIn     1.300000     3.800000
20  USER_0021  2026-03-22   WhatsApp     7.600000     5.800000
21  USER_0022  2026-02-18   LinkedIn     5.300000     8.800000
22  USER_0023  2026-04-03    YouTube     6.600000     6.500000
23  USER_0024  2026-02-13    YouTube     3.100000     4.400000
24  USER_0025  2026-04-23   Snapchat     9.200000     7.700000
25  USER_0026  2026-04-22   Snapchat     8.100000     6.300000
26  USER_0027  2026-02-17   WhatsApp     5.400000     7.800000
27  USER_0028  2026-03-18   Telegram     4.900000     4.100000
28  USER_0029  2026-01-31  Instagram     2.700000     6.600000
29  USER_0030  2026-04-04   LinkedIn     7.800000     8.900000
30  USER_0031  2026-01-17   LinkedIn     9.000000     4.400000
31  USER_0032  2026-02-24   Facebook     8.900000     7.700000
32  USER_0033  2026-04-02   Snapchat     4.100000     7.200000
33  USER_0034  2026-04-26   LinkedIn     1.600000     6.258639
34  USER_0035  2026-03-17   Facebook     5.800000     3.500000
35  USER_0036  2026-01-08   Facebook     1.100000     3.700000
36  USER_0037  2026-03-07   Facebook     3.000000     6.200000
37  USER_0038  2026-04-03   LinkedIn     2.700000     6.100000
38  USER_0039  2026-01-13    YouTube     6.400000     5.400000
39  USER_0040  2026-04-21  Instagram     6.600000     6.258639
40  USER_0041  2026-02-21   Telegram     7.700000     4.100000
41  USER_0042  2026-03-10   LinkedIn     1.800000     4.500000
42  USER_0043  2026-04-22    YouTube     4.500000     8.200000
43  USER_0044  2026-01-07  Instagram     9.200000     8.600000
44  USER_0045  2026-02-22   LinkedIn     5.227411     8.300000
45  USER_0046  2026-02-18  Instagram     9.400000     5.000000
46  USER_0047  2026-02-24   LinkedIn     1.900000     5.100000
47  USER_0048  2026-04-05  Instagram     7.200000     3.800000
48  USER_0049         NaN   WhatsApp     1.000000     6.300000
49  USER_0050  2026-03-18    YouTube     6.600000     4.800000

    Productivity_Score      Mood  Study_Hours  Notification_Count  \
0               94.000     Tired          5.5                  67
1               53.000   Focused          1.2                 141
2               91.000   Focused          2.9                 105
3               31.000     Tired          2.6                 228
4               37.000   Neutral          6.2                 268
5               73.000     Happy          5.7                 266
6               84.000      Lazy          7.2                 129
7               29.000     Happy          1.6                 225
8               50.785   Focused          4.0                  50
9               91.000     Happy          1.2                 104
10              17.000   Neutral          2.5                 214
11              76.000      Lazy          4.5                  21
12              28.000     Tired          1.2                 219
13              53.000   Neutral          2.4                 155
14              53.000     Tired          5.5                 252
15              46.000     Tired          4.8                 166
16              71.000  Stressed          2.5                 236
17              80.000      Lazy          5.1                 304
18              31.000     Tired          6.7                 269
19              90.000     Tired          1.0                  99
20              46.000  Stressed          6.6                 117
21              62.000   Neutral          5.9                 171
22              40.000   Neutral          3.4                 131
23              78.000   Neutral          2.1                  49
24              10.000     Happy          7.7                 316
25              35.000     Tired          3.4                 297
26              40.000     Happy          1.6                  51
27              55.000      Lazy          1.7                 180
28              81.000     Happy          6.9                  49
29              14.000     Tired          5.2                  45
30              10.000   Focused          6.6                 319
31              10.000     Tired          6.1                 264
32              63.000  Stressed          4.8                 277
33              85.000     Happy          7.8                 291
34              30.000   Neutral          3.6                 100
35              90.000     Happy          4.9                  49
36              67.000     Tired          6.8                 280
37              73.000     Tired          5.3                  61
38              36.000  Stressed          7.0                 115
39              53.000     Happy          5.0                  55
40              38.000     Tired          5.9                 324
41              82.000     Tired          1.3                  54
42              50.000       NaN          2.6                 140
43              26.000     Tired          3.0                 226
44              66.000     Tired          1.6                  81
45              10.000      Lazy          2.6                 311
46              86.000   Focused          1.7                 146
47              20.000  Stressed          2.9                 316
48              92.000     Happy          5.4                 324
49              53.000   Focused          3.6                  40

    Screen_Unlocks Weekend_Usage
0             65.0            No
1             87.0            No
2             75.0           Yes
3             24.0            No
4             59.0            No
5             83.0           Yes
6             34.0            No
7             42.0            No
8             15.0            No
9            100.0            No
10            65.0           Yes
11            10.0            No
12            76.0           Yes
13           113.0           NaN
14            78.0            No
15            97.0            No
16           102.0           Yes
17           104.0            No
18           104.0            No
19            95.0            No
20            35.0           Yes
21            56.0            No
22            65.0           Yes
23            18.0           Yes
24            95.0            No
25            52.0           Yes
26            89.0           Yes
27            50.0            No
28            94.0           Yes
29           118.0            No
30            25.0           Yes
31           102.0           Yes
32            48.0            No
33            74.0            No
34            49.0            No
35            95.0           NaN
36            62.0            No
37            51.0            No
38            61.0            No
39            99.0            No
40            47.0            No
41            80.0            No
42            26.0            No
43            34.0           Yes
44            63.0            No
45            95.0           Yes
46            58.0           Yes
47            96.0            No
48           105.0           Yes
49            32.0           Yes

In [9]:
print(df[numeric_cols].isnull().sum())

Usage_Hours           0
Sleep_Hours           0
Productivity_Score    0
Study_Hours           0
Notification_Count    0
Screen_Unlocks        0
dtype: int64

In [10]:

object_cols = df.select_dtypes(include='object').columns

object_cols = object_cols.drop('Date')

df[object_cols] = df[object_cols].fillna("Unknown")
df.head(50)

,User_ID,Date,App_Name,Usage_Hours,Sleep_Hours,Productivity_Score,Mood,Study_Hours,Notification_Count,Screen_Unlocks,Weekend_Usage
0,USER_0001,2026-03-23,YouTube,0.700000,5.000000,94.000,Tired,5.5,67,65.0,No
1,USER_0002,2026-04-05,YouTube,6.600000,8.400000,53.000,Focused,1.2,141,87.0,No
2,USER_0003,2026-02-24,Instagram,0.800000,4.700000,91.000,Focused,2.9,105,75.0,Yes
3,USER_0004,2026-01-04,Facebook,6.900000,7.400000,31.000,Tired,2.6,228,24.0,No
4,USER_0005,2026-02-27,Snapchat,7.800000,3.500000,37.000,Neutral,6.2,268,59.0,No
5,USER_0006,2026-02-24,Telegram,3.000000,4.700000,73.000,Happy,5.7,266,83.0,Yes
6,USER_0007,2026-01-12,Twitter,1.400000,8.200000,84.000,Lazy,7.2,129,34.0,No
7,USER_0008,2026-04-14,Instagram,7.100000,6.400000,29.000,Happy,1.6,225,42.0,No
8,USER_0009,2026-03-12,Snapchat,8.000000,6.900000,50.785,Focused,4.0,50,15.0,No
9,USER_0010,2026-01-25,YouTube,0.900000,4.800000,91.000,Happy,1.2,104,100.0,No
10,USER_0011,2026-04-20,Facebook,8.300000,5.600000,17.000,Neutral,2.5,214,65.0,Yes
11,USER_0012,2026-04-17,Telegram,2.000000,5.500000,76.000,Lazy,4.5,21,10.0,No
12,USER_0013,2026-03-31,YouTube,6.000000,4.400000,28.000,Tired,1.2,219,76.0,Yes
13,USER_0014,2026-01-21,LinkedIn,3.900000,6.258639,53.000,Neutral,2.4,155,113.0,Unknown
14,USER_0015,2026-03-13,Facebook,6.700000,8.100000,53.000,Tired,5.5,252,78.0,No
15,USER_0016,2026-04-16,Instagram,7.700000,5.700000,46.000,Tired,4.8,166,97.0,No
16,USER_0017,2026-04-27,Telegram,2.400000,6.200000,71.000,Stressed,2.5,236,102.0,Yes
17,USER_0018,2026-01-19,Snapchat,1.800000,7.600000,80.000,Lazy,5.1,304,104.0,No
18,USER_0019,NaN,Twitter,8.600000,5.700000,31.000,Tired,6.7,269,104.0,No
19,USER_0020,2026-03-07,LinkedIn,1.300000,3.800000,90.000,Tired,1.0,99,95.0,No
20,USER_0021,2026-03-22,WhatsApp,7.600000,5.800000,46.000,Stressed,6.6,117,35.0,Yes
21,USER_0022,2026-02-18,LinkedIn,5.300000,8.800000,62.000,Neutral,5.9,171,56.0,No
22,USER_0023,2026-04-03,YouTube,6.600000,6.500000,40.000,Neutral,3.4,131,65.0,Yes
23,USER_0024,2026-02-13,YouTube,3.100000,4.400000,78.000,Neutral,2.1,49,18.0,Yes
24,USER_0025,2026-04-23,Snapchat,9.200000,7.700000,10.000,Happy,7.7,316,95.0,No
25,USER_0026,2026-04-22,Snapchat,8.100000,6.300000,35.000,Tired,3.4,297,52.0,Yes
26,USER_0027,2026-02-17,WhatsApp,5.400000,7.800000,40.000,Happy,1.6,51,89.0,Yes
27,USER_0028,2026-03-18,Telegram,4.900000,4.100000,55.000,Lazy,1.7,180,50.0,No
28,USER_0029,2026-01-31,Instagram,2.700000,6.600000,81.000,Happy,6.9,49,94.0,Yes
29,USER_0030,2026-04-04,LinkedIn,7.800000,8.900000,14.000,Tired,5.2,45,118.0,No
30,USER_0031,2026-01-17,LinkedIn,9.000000,4.400000,10.000,Focused,6.6,319,25.0,Yes
31,USER_0032,2026-02-24,Facebook,8.900000,7.700000,10.000,Tired,6.1,264,102.0,Yes
32,USER_0033,2026-04-02,Snapchat,4.100000,7.200000,63.000,Stressed,4.8,277,48.0,No
33,USER_0034,2026-04-26,LinkedIn,1.600000,6.258639,85.000,Happy,7.8,291,74.0,No
34,USER_0035,2026-03-17,Facebook,5.800000,3.500000,30.000,Neutral,3.6,100,49.0,No
35,USER_0036,2026-01-08,Facebook,1.100000,3.700000,90.000,Happy,4.9,49,95.0,Unknown
36,USER_0037,2026-03-07,Facebook,3.000000,6.200000,67.000,Tired,6.8,280,62.0,No
37,USER_0038,2026-04-03,LinkedIn,2.700000,6.100000,73.000,Tired,5.3,61,51.0,No
38,USER_0039,2026-01-13,YouTube,6.400000,5.400000,36.000,Stressed,7.0,115,61.0,No
39,USER_0040,2026-04-21,Instagram,6.600000,6.258639,53.000,Happy,5.0,55,99.0,No
40,USER_0041,2026-02-21,Telegram,7.700000,4.100000,38.000,Tired,5.9,324,47.0,No
41,USER_0042,2026-03-10,LinkedIn,1.800000,4.500000,82.000,Tired,1.3,54,80.0,No
42,USER_0043,2026-04-22,YouTube,4.500000,8.200000,50.000,Unknown,2.6,140,26.0,No
43,USER_0044,2026-01-07,Instagram,9.200000,8.600000,26.000,Tired,3.0,226,34.0,Yes
44,USER_0045,2026-02-22,LinkedIn,5.227411,8.300000,66.000,Tired,1.6,81,63.0,No
45,USER_0046,2026-02-18,Instagram,9.400000,5.000000,10.000,Lazy,2.6,311,95.0,Yes
46,USER_0047,2026-02-24,LinkedIn,1.900000,5.100000,86.000,Focused,1.7,146,58.0,Yes
47,USER_0048,2026-04-05,Instagram,7.200000,3.800000,20.000,Stressed,2.9,316,96.0,No
48,USER_0049,NaN,WhatsApp,1.000000,6.300000,92.000,Happy,5.4,324,105.0,Yes
49,USER_0050,2026-03-18,YouTube,6.600000,4.800000,53.000,Focused,3.6,40,32.0,Yes

In [11]:
df['Date'] = df['Date'].ffill()
df.head(50)

,User_ID,Date,App_Name,Usage_Hours,Sleep_Hours,Productivity_Score,Mood,Study_Hours,Notification_Count,Screen_Unlocks,Weekend_Usage
0,USER_0001,2026-03-23,YouTube,0.700000,5.000000,94.000,Tired,5.5,67,65.0,No
1,USER_0002,2026-04-05,YouTube,6.600000,8.400000,53.000,Focused,1.2,141,87.0,No
2,USER_0003,2026-02-24,Instagram,0.800000,4.700000,91.000,Focused,2.9,105,75.0,Yes
3,USER_0004,2026-01-04,Facebook,6.900000,7.400000,31.000,Tired,2.6,228,24.0,No
4,USER_0005,2026-02-27,Snapchat,7.800000,3.500000,37.000,Neutral,6.2,268,59.0,No
5,USER_0006,2026-02-24,Telegram,3.000000,4.700000,73.000,Happy,5.7,266,83.0,Yes
6,USER_0007,2026-01-12,Twitter,1.400000,8.200000,84.000,Lazy,7.2,129,34.0,No
7,USER_0008,2026-04-14,Instagram,7.100000,6.400000,29.000,Happy,1.6,225,42.0,No
8,USER_0009,2026-03-12,Snapchat,8.000000,6.900000,50.785,Focused,4.0,50,15.0,No
9,USER_0010,2026-01-25,YouTube,0.900000,4.800000,91.000,Happy,1.2,104,100.0,No
10,USER_0011,2026-04-20,Facebook,8.300000,5.600000,17.000,Neutral,2.5,214,65.0,Yes
11,USER_0012,2026-04-17,Telegram,2.000000,5.500000,76.000,Lazy,4.5,21,10.0,No
12,USER_0013,2026-03-31,YouTube,6.000000,4.400000,28.000,Tired,1.2,219,76.0,Yes
13,USER_0014,2026-01-21,LinkedIn,3.900000,6.258639,53.000,Neutral,2.4,155,113.0,Unknown
14,USER_0015,2026-03-13,Facebook,6.700000,8.100000,53.000,Tired,5.5,252,78.0,No
15,USER_0016,2026-04-16,Instagram,7.700000,5.700000,46.000,Tired,4.8,166,97.0,No
16,USER_0017,2026-04-27,Telegram,2.400000,6.200000,71.000,Stressed,2.5,236,102.0,Yes
17,USER_0018,2026-01-19,Snapchat,1.800000,7.600000,80.000,Lazy,5.1,304,104.0,No
18,USER_0019,2026-01-19,Twitter,8.600000,5.700000,31.000,Tired,6.7,269,104.0,No
19,USER_0020,2026-03-07,LinkedIn,1.300000,3.800000,90.000,Tired,1.0,99,95.0,No
20,USER_0021,2026-03-22,WhatsApp,7.600000,5.800000,46.000,Stressed,6.6,117,35.0,Yes
21,USER_0022,2026-02-18,LinkedIn,5.300000,8.800000,62.000,Neutral,5.9,171,56.0,No
22,USER_0023,2026-04-03,YouTube,6.600000,6.500000,40.000,Neutral,3.4,131,65.0,Yes
23,USER_0024,2026-02-13,YouTube,3.100000,4.400000,78.000,Neutral,2.1,49,18.0,Yes
24,USER_0025,2026-04-23,Snapchat,9.200000,7.700000,10.000,Happy,7.7,316,95.0,No
25,USER_0026,2026-04-22,Snapchat,8.100000,6.300000,35.000,Tired,3.4,297,52.0,Yes
26,USER_0027,2026-02-17,WhatsApp,5.400000,7.800000,40.000,Happy,1.6,51,89.0,Yes
27,USER_0028,2026-03-18,Telegram,4.900000,4.100000,55.000,Lazy,1.7,180,50.0,No
28,USER_0029,2026-01-31,Instagram,2.700000,6.600000,81.000,Happy,6.9,49,94.0,Yes
29,USER_0030,2026-04-04,LinkedIn,7.800000,8.900000,14.000,Tired,5.2,45,118.0,No
30,USER_0031,2026-01-17,LinkedIn,9.000000,4.400000,10.000,Focused,6.6,319,25.0,Yes
31,USER_0032,2026-02-24,Facebook,8.900000,7.700000,10.000,Tired,6.1,264,102.0,Yes
32,USER_0033,2026-04-02,Snapchat,4.100000,7.200000,63.000,Stressed,4.8,277,48.0,No
33,USER_0034,2026-04-26,LinkedIn,1.600000,6.258639,85.000,Happy,7.8,291,74.0,No
34,USER_0035,2026-03-17,Facebook,5.800000,3.500000,30.000,Neutral,3.6,100,49.0,No
35,USER_0036,2026-01-08,Facebook,1.100000,3.700000,90.000,Happy,4.9,49,95.0,Unknown
36,USER_0037,2026-03-07,Facebook,3.000000,6.200000,67.000,Tired,6.8,280,62.0,No
37,USER_0038,2026-04-03,LinkedIn,2.700000,6.100000,73.000,Tired,5.3,61,51.0,No
38,USER_0039,2026-01-13,YouTube,6.400000,5.400000,36.000,Stressed,7.0,115,61.0,No
39,USER_0040,2026-04-21,Instagram,6.600000,6.258639,53.000,Happy,5.0,55,99.0,No
40,USER_0041,2026-02-21,Telegram,7.700000,4.100000,38.000,Tired,5.9,324,47.0,No
41,USER_0042,2026-03-10,LinkedIn,1.800000,4.500000,82.000,Tired,1.3,54,80.0,No
42,USER_0043,2026-04-22,YouTube,4.500000,8.200000,50.000,Unknown,2.6,140,26.0,No
43,USER_0044,2026-01-07,Instagram,9.200000,8.600000,26.000,Tired,3.0,226,34.0,Yes
44,USER_0045,2026-02-22,LinkedIn,5.227411,8.300000,66.000,Tired,1.6,81,63.0,No
45,USER_0046,2026-02-18,Instagram,9.400000,5.000000,10.000,Lazy,2.6,311,95.0,Yes
46,USER_0047,2026-02-24,LinkedIn,1.900000,5.100000,86.000,Focused,1.7,146,58.0,Yes
47,USER_0048,2026-04-05,Instagram,7.200000,3.800000,20.000,Stressed,2.9,316,96.0,No
48,USER_0049,2026-04-05,WhatsApp,1.000000,6.300000,92.000,Happy,5.4,324,105.0,Yes
49,USER_0050,2026-03-18,YouTube,6.600000,4.800000,53.000,Focused,3.6,40,32.0,Yes

In [12]:
print(df[object_cols].isnull().sum())

User_ID          0
App_Name         0
Mood             0
Weekend_Usage    0
dtype: int64

In [13]:
print(df['Date'].isnull().sum())

0

In [14]:
df.isnull().sum()

User_ID               0
Date                  0
App_Name              0
Usage_Hours           0
Sleep_Hours           0
Productivity_Score    0
Mood                  0
Study_Hours           0
Notification_Count    0
Screen_Unlocks        0
Weekend_Usage         0
dtype: int64

In [15]:
(df == "ERROR_VALUE").sum()

User_ID               0
Date                  0
App_Name              3
Usage_Hours           0
Sleep_Hours           0
Productivity_Score    0
Mood                  0
Study_Hours           0
Notification_Count    0
Screen_Unlocks        0
Weekend_Usage         2
dtype: int64

In [16]:
df.replace("ERROR_VALUE", pd.NA, inplace=True)

In [17]:
print((df == "ERROR_VALUE").sum())

User_ID               0
Date                  0
App_Name              0
Usage_Hours           0
Sleep_Hours           0
Productivity_Score    0
Mood                  0
Study_Hours           0
Notification_Count    0
Screen_Unlocks        0
Weekend_Usage         0
dtype: int64

In [18]:
print(df.isnull().sum())

User_ID               0
Date                  0
App_Name              3
Usage_Hours           0
Sleep_Hours           0
Productivity_Score    0
Mood                  0
Study_Hours           0
Notification_Count    0
Screen_Unlocks        0
Weekend_Usage         2
dtype: int64

In [19]:
df[object_cols] = df[object_cols].fillna("Unknown")

In [20]:
print(df.isnull().sum())

User_ID               0
Date                  0
App_Name              0
Usage_Hours           0
Sleep_Hours           0
Productivity_Score    0
Mood                  0
Study_Hours           0
Notification_Count    0
Screen_Unlocks        0
Weekend_Usage         0
dtype: int64

In [24]:
print(df.duplicated().sum())

0

In [26]:
df.to_csv("cleaned_dataset.csv", index=False)